#!/usr/bin/env bun
/**
 * Setup Morpheus Node
 *
 * Downloads the proxy-router binary from Morpheus releases.
 * This is required to run mor-diem-sdk locally (staking MOR, not using api.mor.org).
 */

import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'
import { mnemonicToAccount } from 'viem/accounts'

const MORPHEUS_DIR = join(homedir(), '.morpheus')
const BINARY_NAME = process.platform === 'win32' ? 'proxy-router.exe' : 'proxy-router'
const BINARY_PATH = join(MORPHEUS_DIR, BINARY_NAME)
const ENV_PATH = join(MORPHEUS_DIR, '.env')
const DATA_DIR = join(MORPHEUS_DIR, 'data')

// Base Mainnet configuration for Morpheus
const BASE_CONFIG = `# Morpheus Node Configuration (Base Mainnet)
# Generated by mor-diem-sdk setup

# Your wallet private key (required for staking)
# Export from your wallet or derive from mnemonic
WALLET_PRIVATE_KEY=

# Base Mainnet contracts
DIAMOND_CONTRACT_ADDRESS=0x6aBE1d282f72B474E54527D93b979A4f64d3030a
MOR_TOKEN_ADDRESS=0x7431aDa8a591C955a994a21710752EF9b882b8e3
ETH_NODE_CHAIN_ID=8453
BLOCKSCOUT_API_URL=https://base.blockscout.com/api/v2
ENVIRONMENT=production

# Paths
COOKIE_FILE_PATH=./.cookie
PROXY_STORAGE_PATH=./data/

# Network
PROXY_ADDRESS=0.0.0.0:9081
WEB_ADDRESS=0.0.0.0:8082
WEB_PUBLIC_URL=http://localhost:8082

# RPC (uses public Base RPC by default, set your own for better reliability)
ETH_NODE_ADDRESS=
ETH_NODE_USE_SUBSCRIPTIONS=false
ETH_NODE_LEGACY_TX=false

# Logging
LOG_COLOR=true
LOG_LEVEL_APP=info

# Timeouts
LLM_TIMEOUT=4m
CNODE_PNODE_TIMEOUT=90s
CNODE_PNODE_MAX_RETRIES=3
`

const RELEASES_URL =
	'https://api.github.com/repos/MorpheusAIs/Morpheus-Lumerin-Node/releases/latest'

interface Asset {
	name: string
	browser_download_url: string
}

interface Release {
	tag_name: string
	assets: Asset[]
}

function getPlatformAssetPattern(): RegExp {
	const platform = process.platform
	const arch = process.arch

	// Asset names look like: mac-arm64-morpheus-router-5.14.0
	if (platform === 'darwin') {
		const macArch = arch === 'arm64' ? 'arm64' : 'x64'
		return new RegExp(`mac-${macArch}-morpheus-router-`)
	} else if (platform === 'linux') {
		const linuxArch = arch === 'arm64' ? 'arm64' : 'x86_64'
		return new RegExp(`linux-${linuxArch}-morpheus-router-`)
	} else if (platform === 'win32') {
		return /win-x64-morpheus-router-.*\.exe$/
	}
	throw new Error(`Unsupported platform: ${platform} ${arch}`)
}

async function main() {
	console.log('🔧 Setting up Morpheus Node...\n')

	// Check if already installed
	if (existsSync(BINARY_PATH)) {
		console.log(`✅ Morpheus Node already installed at ${BINARY_PATH}`)
		console.log('   To reinstall, delete it and run this script again.\n')
		return
	}

	// Create directory
	if (!existsSync(MORPHEUS_DIR)) {
		mkdirSync(MORPHEUS_DIR, { recursive: true })
		console.log(`📁 Created ${MORPHEUS_DIR}`)
	}

	// Fetch latest release
	console.log('📡 Fetching latest release from GitHub...')
	const releaseRes = await fetch(RELEASES_URL)
	if (!releaseRes.ok) {
		throw new Error(`Failed to fetch releases: ${releaseRes.status}`)
	}
	const release: Release = await releaseRes.json()
	console.log(`   Found ${release.tag_name}`)

	// Find matching asset
	const assetPattern = getPlatformAssetPattern()
	const asset = release.assets.find((a) => assetPattern.test(a.name))
	if (!asset) {
		console.error(`\n❌ No binary found for ${process.platform} ${process.arch}`)
		console.error(`   Looking for pattern: ${assetPattern}`)
		console.error(`   Available assets: ${release.assets.map((a) => a.name).join(', ')}`)
		console.error(`\n   Download manually from:`)
		console.error(`   https://github.com/MorpheusAIs/Morpheus-Lumerin-Node/releases\n`)
		process.exit(1)
	}

	// Download binary
	console.log(`📥 Downloading ${asset.name}...`)
	const binaryRes = await fetch(asset.browser_download_url)
	if (!binaryRes.ok) {
		throw new Error(`Failed to download: ${binaryRes.status}`)
	}
	const binaryData = await binaryRes.arrayBuffer()
	await Bun.write(BINARY_PATH, binaryData)
	console.log(`   Saved to ${BINARY_PATH}`)

	// Make executable
	if (process.platform !== 'win32') {
		chmodSync(BINARY_PATH, 0o755)
		console.log('   Made executable')
	}

	// Create data directory
	if (!existsSync(DATA_DIR)) {
		mkdirSync(DATA_DIR, { recursive: true })
		console.log(`📁 Created ${DATA_DIR}`)
	}

	// Create/update config file with private key from mnemonic
	let config = BASE_CONFIG
	const mnemonic = process.env.MOR_MNEMONIC

	if (mnemonic) {
		try {
			const account = mnemonicToAccount(mnemonic)
			// Get private key - viem stores it internally, we need to extract it
			// The account object doesn't expose privateKey directly, so we use a workaround
			const { HDKey } = await import('@scure/bip32')
			const { mnemonicToSeedSync } = await import('@scure/bip39')
			const seed = mnemonicToSeedSync(mnemonic)
			const hdKey = HDKey.fromMasterSeed(seed)
			const childKey = hdKey.derive("m/44'/60'/0'/0/0")
			const privateKey = `0x${Buffer.from(childKey.privateKey!).toString('hex')}`

			config = config.replace('WALLET_PRIVATE_KEY=', `WALLET_PRIVATE_KEY=${privateKey}`)
			console.log(`🔑 Derived private key from MOR_MNEMONIC`)
			console.log(`   Address: ${account.address}`)
		} catch (e) {
			console.warn(`⚠️  Could not derive key from mnemonic: ${e.message}`)
		}
	}

	if (!existsSync(ENV_PATH)) {
		writeFileSync(ENV_PATH, config)
		console.log(`📝 Created ${ENV_PATH}`)
		if (!mnemonic) {
			console.log(
				'   ⚠️  Set MOR_MNEMONIC in .env and re-run setup, or add WALLET_PRIVATE_KEY manually',
			)
		}
	} else {
		// Update existing config with private key if we have it and it's missing
		if (mnemonic) {
			let existingConfig = readFileSync(ENV_PATH, 'utf-8')
			if (
				existingConfig.includes('WALLET_PRIVATE_KEY=\n') ||
				existingConfig.includes('WALLET_PRIVATE_KEY=$')
			) {
				existingConfig = existingConfig.replace(
					/WALLET_PRIVATE_KEY=.*\n/,
					config.match(/WALLET_PRIVATE_KEY=.*\n/)![0],
				)
				writeFileSync(ENV_PATH, existingConfig)
				console.log(`📝 Updated ${ENV_PATH} with private key`)
			}
		} else {
			console.log(`📝 Config already exists at ${ENV_PATH}`)
		}
	}

	console.log('\n✅ Morpheus Node installed!\n')
	if (mnemonic) {
		console.log('Next steps:')
		console.log(`   1. Start the node: cd ${MORPHEUS_DIR} && ./proxy-router`)
		console.log(`   2. Start the proxy: bun run proxy`)
		console.log(`   3. Run the CLI: bun run cli\n`)
	} else {
		console.log('Next steps:')
		console.log(`   1. Set MOR_MNEMONIC in .env and re-run: bun run setup`)
		console.log(`      OR add WALLET_PRIVATE_KEY to ${ENV_PATH}`)
		console.log(`   2. Start the node: cd ${MORPHEUS_DIR} && ./proxy-router`)
		console.log(`   3. Start the proxy: bun run proxy\n`)
	}
	console.log('The node will:')
	console.log('   - Listen on port 9081')
	console.log('   - Create .cookie for authentication')
	console.log('   - Manage your MOR staking on Base\n')
}

main().catch((err) => {
	console.error('❌ Setup failed:', err.message)
	process.exit(1)
})
